// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function PickWorkingDir() {
  return window['go']['main']['App']['PickWorkingDir']();
}

export function PlanApprove(arg1) {
  return window['go']['main']['App']['PlanApprove'](arg1);
}

export function PlanPreview(arg1) {
  return window['go']['main']['App']['PlanPreview'](arg1);
}

export function PlanReject(arg1) {
  return window['go']['main']['App']['PlanReject'](arg1);
}

export function PlansInbox(arg1) {
  return window['go']['main']['App']['PlansInbox'](arg1);
}

export function QueueCancel(arg1) {
  return window['go']['main']['App']['QueueCancel'](arg1);
}

export function QueueInspect(arg1) {
  return window['go']['main']['App']['QueueInspect'](arg1);
}

export function ResultShow(arg1) {
  return window['go']['main']['App']['ResultShow'](arg1);
}

export function SessionInspect(arg1) {
  return window['go']['main']['App']['SessionInspect'](arg1);
}

export function SetWorkingDir(arg1) {
  return window['go']['main']['App']['SetWorkingDir'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function SubmitRun(arg1) {
  return window['go']['main']['App']['SubmitRun'](arg1);
}
